language: java
jdk:
  - oraclejdk8

# install the newest java.
addons:
  chrome: stable # have Travis install chrome stable.
  apt:
    packages:
      - oracle-java8-installer

dist: trusty # needs Ubuntu Trusty
# Note: if you switch to sudo: false, you'll need to launch chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: required

cache:
  yarn: true
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_script:
  - sudo apt-get update
  - sudo apt-get install -y wget zip unzip
  - sudo mkdir -p /opt/android-sdk-linux
  - export ANDROID_HOME=/opt/android-sdk-linux
  - wget -q "https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip" -O sdk-tools.zip
  - sudo unzip -q -d $ANDROID_HOME sdk-tools.zip
  - rm sdk-tools.zip
  - export PATH=$PATH:$ANDROID_HOME/tools/bin
  - echo y | sdkmanager --install 'platforms;android-28' "build-tools;28.0.3" "platform-tools"
  - echo "sdk.dir=$ANDROID_HOME/Sdk" > local.properties

# configure xvfb screen.
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# skip install stage.
install: true
